#!/bin/sh
# Author: Noel Colon

# post-checkout

# This hook is invoked when a git-checkout(1) or git-switch(1) is run after having updated the worktree.
# The hook is given three parameters: the ref of the previous HEAD, the ref of the new HEAD (which may or may not have changed), and a flag indicating whether the checkout was a branch checkout (changing branches, flag=1) or a file checkout (retrieving a file from the index, flag=0).
# This hook cannot affect the outcome of git switch or git checkout.

# If a commit prefix is set, prompt during git checkout branch whether to unset it

PREFIX=$(git config --get commit.prefix)
[ "$3" == 1 ] && [ -n "$PREFIX" ] && exec < /dev/tty && echo "Unset git commit prefix? [y/n]: " && read choice
[ "$choice" == 'y' ] && git config --unset commit.prefix && echo "Prefix unset: $PREFIX"
